### ISSUE TITLE
Themes don't work with multi monitors configuration

### ISSUE THREAD

**Issue by piomiq** [Rokin05/SDDM-Themes#2]
Hi

I have two displays, so: primary 2560x1440, secondary 1920x1080.
The problem I experience I described here: https://github.com/sddm/sddm/issues/1219
I tested couple your themes, so "sober" and "mount" and in result the effect is the same like in screenshots I attached to issue in mentioned url, so are displayed two screens (bigger and smaller - one lies on second and smaller is active). I will attach screen for "mount" theme.
I use Arch Linux distribution, where sddm in version sddm 0.18.1-1 and Qt5 5.14. Of course I have installed required packages, so:
qt5-graphicaleffects 5.14.0-1
qt5-quickcontrols2 5.14.0-1

Seems below code:
> active: primaryScreen

placed in section `Loader`
is not handled correctly by the newest sddm.

**Comment by Rokin05** [comment]
In the case of multi-screen, this depends essentially on the "primaryScreen" variable and unfortunately it is not possible to provide a more precise management in the QtQuick code.

The problem that you meet is unfortunately upstream of the theme and I can not solve it in the sddm theme code.
